-- 판단 필요 계정의 체크리스트 항목. item_key는 계산 로직이 읽는 계약이므로 코드와 반드시 일치해야
-- 하며, 서버 시작 시 verify_reference_contract가 이를 검증한다.
INSERT INTO checklist_items (id, account_key, item_key, label, input_type, options, required, display_order)
VALUES
  ('lease_lease_term_months', 'lease', 'lease_term_months', '리스기간(개월)', 'number', '', true, 1),
  ('lease_monthly_payment', 'lease', 'monthly_payment', '월 리스료', 'number', '', true, 2),
  ('lease_discount_rate', 'lease', 'discount_rate', '증분차입이자율(%)', 'number', '', true, 3),
  ('lease_renewal_option', 'lease', 'renewal_option', '연장선택권 행사가 상당히 확실한가?', 'boolean', '', false, 4),
  ('development_technical_feasibility', 'development', 'technical_feasibility', '기술적 실현가능성이 입증되었는가?', 'boolean', '', true, 1),
  ('development_intention_to_complete', 'development', 'intention_to_complete', '완성 의도와 능력이 있는가?', 'boolean', '', true, 2),
  ('development_probable_future_benefits', 'development', 'probable_future_benefits', '미래경제적효익이 개연적인가?', 'boolean', '', true, 3),
  ('development_reliable_measurement', 'development', 'reliable_measurement', '원가를 신뢰성 있게 측정할 수 있는가?', 'boolean', '', true, 4),
  ('revenue_contract_type', 'revenue', 'contract_type', '계약 유형', 'text', '', true, 1),
  ('revenue_performance_obligations', 'revenue', 'performance_obligations', '수행의무', 'text', '', true, 2),
  ('revenue_recognition_timing', 'revenue', 'recognition_timing', '한 시점 또는 기간에 걸친 인식', 'choice', '한 시점 인식/기간에 걸친 인식', true, 3),
  ('revenue_variable_consideration', 'revenue', 'variable_consideration', '변동대가가 있는가?', 'boolean', '', false, 4),
  ('financial_instrument_instrument_terms', 'financial_instrument', 'instrument_terms', '주요 계약조건', 'text', '', true, 1),
  ('financial_instrument_business_model', 'financial_instrument', 'business_model', '보유 사업모형', 'text', '', true, 2),
  ('financial_instrument_sppi_passed', 'financial_instrument', 'sppi_passed', '원금과 이자 지급만으로 구성된 현금흐름(SPPI) 요건을 충족하는가?', 'boolean', '', true, 3),
  ('provision_present_obligation', 'provision', 'present_obligation', '현재의무가 존재하는가?', 'boolean', '', true, 1),
  ('provision_probable_outflow', 'provision', 'probable_outflow', '자원 유출 가능성이 높은가?', 'boolean', '', true, 2),
  ('provision_reliable_estimate', 'provision', 'reliable_estimate', '금액을 신뢰성 있게 추정할 수 있는가?', 'boolean', '', true, 3),
  ('receivables_credit_risk_method', 'receivables', 'credit_risk_method', '기대신용손실 산정 방식', 'text', '', true, 1),
  ('receivables_aging_available', 'receivables', 'aging_available', '연령분석표가 있는가?', 'boolean', '', true, 2),
  ('ppe_measurement_model', 'ppe', 'measurement_model', '측정모형 (원가모형 / 재평가모형)', 'choice', '원가모형/재평가모형', true, 1),
  ('ppe_fair_value', 'ppe', 'fair_value', '재평가모형 선택 시 공정가치', 'number', '', false, 2),
  ('ppe_recoverable_amount', 'ppe', 'recoverable_amount', '회수가능액 (손상검토용, 없으면 0)', 'number', '', false, 3),
  ('deferred_tax_asset_temporary_difference', 'deferred_tax_asset', 'temporary_difference', '차감할 일시적차이 총액', 'number', '', true, 1),
  ('deferred_tax_asset_tax_rate', 'deferred_tax_asset', 'tax_rate', '적용 세율(%)', 'number', '', true, 2),
  ('deferred_tax_asset_realizable', 'deferred_tax_asset', 'realizable', '미래 과세소득으로 회수 가능성이 높은가?', 'boolean', '', true, 3),
  ('retirement_benefit_dbo_amount', 'retirement_benefit', 'dbo_amount', '확정급여채무 현재가치(보험수리적 평가액)', 'number', '', true, 1),
  ('retirement_benefit_plan_assets', 'retirement_benefit', 'plan_assets', '사외적립자산 공정가치', 'number', '', false, 2),
  ('retirement_benefit_discount_rate', 'retirement_benefit', 'discount_rate', '할인율(%)', 'number', '', false, 3),
  ('investment_property_measurement_model', 'investment_property', 'measurement_model', '측정모형 (원가모형 / 공정가치모형)', 'choice', '원가모형/공정가치모형', true, 1),
  ('investment_property_fair_value', 'investment_property', 'fair_value', '공정가치모형 선택 시 공정가치', 'number', '', false, 2),
  ('government_grant_grant_relation', 'government_grant', 'grant_relation', '보조금 성격 (자산관련 / 수익관련)', 'choice', '자산관련/수익관련', true, 1),
  ('government_grant_presentation_method', 'government_grant', 'presentation_method', '자산관련 표시 방법 (자산차감법 / 이연수익법)', 'choice', '자산차감법/이연수익법', true, 2),
  ('borrowing_cost_qualifying_asset', 'borrowing_cost', 'qualifying_asset', '적격자산(취득에 상당한 기간 소요)인가?', 'boolean', '', true, 1),
  ('borrowing_cost_expenditure', 'borrowing_cost', 'expenditure', '적격자산에 대한 평균 지출액', 'number', '', false, 2),
  ('borrowing_cost_capitalization_rate', 'borrowing_cost', 'capitalization_rate', '자본화이자율(%)', 'number', '', false, 3),
  ('borrowing_cost_capitalization_months', 'borrowing_cost', 'capitalization_months', '자본화 기간(개월)', 'number', '', false, 4),
  ('goodwill_accumulated_amortization', 'goodwill', 'accumulated_amortization', '전환일까지 누적 영업권 상각비(K-GAAP)', 'number', '', true, 1),
  ('goodwill_impairment_indicator', 'goodwill', 'impairment_indicator', '손상 징후가 있는가?', 'boolean', '', true, 2),
  ('goodwill_recoverable_amount', 'goodwill', 'recoverable_amount', '회수가능액(손상 징후가 있는 경우)', 'number', '', false, 3),
  ('preferred_shares_mandatory_redemption', 'preferred_shares', 'mandatory_redemption', '의무상환 조항 또는 보유자의 상환청구권이 있는가?', 'boolean', '', true, 1),
  ('preferred_shares_cumulative_dividend', 'preferred_shares', 'cumulative_dividend', '확정 배당(누적적 우선배당) 의무가 있는가?', 'boolean', '', false, 2),
  ('held_for_sale_plan_committed', 'held_for_sale', 'plan_committed', '경영진이 매각계획을 확약했는가?', 'boolean', '', true, 1),
  ('held_for_sale_sale_probable_12m', 'held_for_sale', 'sale_probable_12m', '12개월 이내 매각가능성이 매우 높은가?', 'boolean', '', true, 2),
  ('held_for_sale_fair_value_less_costs', 'held_for_sale', 'fair_value_less_costs', '순공정가치(매각부대원가 차감 후)', 'number', '', true, 3),
  ('compound_conversion_terms', 'compound_instrument', 'conversion_terms', '전환·행사 조건 요약(전환가격, 리픽싱 조항 등)', 'text', '', true, 1),
  ('compound_cash_settlement', 'compound_instrument', 'cash_settlement_possible', '현금결제 가능성 또는 상환 의무가 있는가?', 'boolean', '', true, 2),
  ('compound_fx_or_adjustable', 'compound_instrument', 'fx_or_adjustable', '외화표시이거나 전환가격 조정(리픽싱) 조항이 있는가?', 'boolean', '', false, 3),
  ('derivative_instrument_type', 'derivative', 'instrument_type', '파생상품 유형(선도/스왑/옵션/내재파생 등)', 'text', '', true, 1),
  ('derivative_hedge_designated', 'derivative', 'hedge_designated', '위험회피관계로 공식 지정·문서화되어 있는가?', 'boolean', '', true, 2),
  ('inventory_cost_method', 'inventory', 'cost_method', '원가결정방법', 'choice', '선입선출법/가중평균법/후입선출법/개별법', true, 1),
  ('inventory_fifo_restated_amount', 'inventory', 'fifo_restated_amount', '후입선출법 적용 시 선입선출·가중평균 재계산 금액', 'number', '', false, 2),
  ('inventory_normal_capacity', 'inventory', 'normal_capacity_applied', '고정제조간접비를 정상조업도 기준으로 배부했는가?', 'boolean', '', false, 3),
  ('other_management_memo', 'other', 'management_memo', '경영진 분류 메모', 'text', '', true, 1)
ON CONFLICT (id) DO UPDATE SET
  account_key = excluded.account_key,
  item_key = excluded.item_key,
  label = excluded.label,
  input_type = excluded.input_type,
  options = excluded.options,
  required = excluded.required,
  display_order = excluded.display_order;
