-- K-GAAP 계정명 별칭 → 표준계정 키. 부분 문자열 매칭이라 match_priority(별칭 길이)가 클수록
-- 먼저 검사되어 '금융상품 ⊃ 상품' 같은 충돌을 해결한다.
INSERT INTO kgaap_accounts (id, account_key, kgaap_name, normalized_name, active, match_priority)
VALUES
  ('alias_1', 'cash', '현금및현금성자산', '현금및현금성자산', true, 8),
  ('alias_2', 'cash', '현금', '현금및현금성자산', true, 2),
  ('alias_3', 'cash', 'cash', '현금및현금성자산', true, 4),
  ('alias_4', 'receivables', '매출채권', '매출채권', true, 4),
  ('alias_5', 'receivables', '대손충당금', '매출채권', true, 5),
  ('alias_6', 'receivables', '미수금', '매출채권', true, 3),
  ('alias_7', 'receivables', '미수수익', '매출채권', true, 4),
  ('alias_8', 'receivables', '계약자산', '매출채권', true, 4),
  ('alias_9', 'receivables', 'trade receivable', '매출채권', true, 16),
  ('alias_10', 'financial_instrument', '금융자산', '금융상품', true, 4),
  ('alias_11', 'financial_instrument', '금융부채', '금융상품', true, 4),
  ('alias_12', 'financial_instrument', '금융상품', '금융상품', true, 4),
  ('alias_13', 'financial_instrument', '파생상품', '금융상품', true, 4),
  ('alias_14', 'financial_instrument', '전환사채', '금융상품', true, 4),
  ('alias_15', 'financial_instrument', '장기차입금', '금융상품', true, 5),
  ('alias_16', 'financial_instrument', '단기차입금', '금융상품', true, 5),
  ('alias_17', 'financial_instrument', '차입금', '금융상품', true, 3),
  ('alias_18', 'financial_instrument', '사채상환할증금', '금융상품', true, 7),
  ('alias_19', 'financial_instrument', '전환권조정', '금융상품', true, 5),
  ('alias_20', 'inventory', '재고자산', '재고자산', true, 4),
  ('alias_21', 'inventory', '상품', '재고자산', true, 2),
  ('alias_22', 'inventory', '제품', '재고자산', true, 2),
  ('alias_23', 'inventory', '원재료', '재고자산', true, 3),
  ('alias_24', 'inventory', 'inventory', '재고자산', true, 9),
  ('alias_25', 'lease', '리스', '리스', true, 2),
  ('alias_26', 'lease', '사용권자산', '리스', true, 5),
  ('alias_27', 'lease', '리스부채', '리스', true, 4),
  ('alias_28', 'lease', 'lease', '리스', true, 5),
  ('alias_29', 'development', '개발비', '개발비', true, 3),
  ('alias_30', 'development', '무형자산', '개발비', true, 4),
  ('alias_31', 'development', 'development', '개발비', true, 11),
  ('alias_32', 'revenue', '매출액', '수익', true, 3),
  ('alias_33', 'revenue', '매출', '수익', true, 2),
  ('alias_34', 'revenue', '영업수익', '수익', true, 4),
  ('alias_35', 'revenue', '수익', '수익', true, 2),
  ('alias_36', 'revenue', 'revenue', '수익', true, 7),
  ('alias_37', 'retirement_benefit', '퇴직급여충당부채', '퇴직급여충당부채', true, 8),
  ('alias_38', 'retirement_benefit', '확정급여채무', '퇴직급여충당부채', true, 6),
  ('alias_39', 'retirement_benefit', '순확정급여부채', '퇴직급여충당부채', true, 7),
  ('alias_40', 'retirement_benefit', '퇴직급여', '퇴직급여충당부채', true, 4),
  ('alias_41', 'provision', '충당부채', '충당부채', true, 4),
  ('alias_42', 'provision', 'provision', '충당부채', true, 9),
  ('alias_43', 'investment_property', '투자부동산', '투자부동산', true, 5),
  ('alias_44', 'government_grant', '정부보조금', '정부보조금', true, 5),
  ('alias_45', 'government_grant', '국고보조금', '정부보조금', true, 5),
  ('alias_46', 'borrowing_cost', '차입원가', '차입원가', true, 4),
  ('alias_47', 'ppe', '유형자산', '유형자산', true, 4),
  ('alias_48', 'ppe', '토지', '유형자산', true, 2),
  ('alias_49', 'ppe', '건물', '유형자산', true, 2),
  ('alias_50', 'ppe', '기계장치', '유형자산', true, 4),
  ('alias_51', 'deferred_tax_asset', '이연법인세자산', '이연법인세자산', true, 7),
  ('alias_52', 'deferred_tax_liability', '이연법인세부채', '이연법인세부채', true, 7)
ON CONFLICT (id) DO UPDATE SET
  account_key = excluded.account_key,
  kgaap_name = excluded.kgaap_name,
  normalized_name = excluded.normalized_name,
  active = excluded.active,
  match_priority = excluded.match_priority;
